id: IBA767C2D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:03:24+00:00'
last_modified: '2022-06-08T04:47:17.570766+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD95810
  title: གསུང་འཐོར་བུ། བློ་གྲོས་རྒྱལ་མཚན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3FCB:
      image_group_id: I1PD95840
      title: ''
      total_pages: 470
      order: 1
      base_file: 3FCB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
