id: P005541
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD95810
  title: གསུང་འཐོར་བུ། བློ་གྲོས་རྒྱལ་མཚན
  author: ''
  volumes:
    db356f47f5e349abbf06b55a5366afbb:
      image_group_id: I1PD95840
      title: ''
      volume_number: 1
      total_pages: 470
      base_file: v001.txt
